version: '3.1'

services:
  app:
    build: .
    environment:
      regexEmail: "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z][cl])$$"
      emailPattern: "aaaaaaa@dominio.cl"
      regexPassword: "^(?=.{4,}$$)(?=(?:.*[A-Z]))(?=.*[a-z])(?=(?:.*[0-9]){2}).*"
      inValidPasswordMessage: "La contraseña debe tener una mayúscula, al menos una minuscula y 2 digitos."
    restart: always
    ports:
      - 8080:8080